name: Atualizar USDW Oracle

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-oracle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar oráculo
        run: python oracle_updater.py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
